### PR TITLE
Fix UTF-8 decoding errors

### LINKED ISSUE #1: Decoding Google Maps point KMZ file ends up with a panic
Hi!
I am getting an error when attempting to import a KMZ file from a user-submitted Google map.
Currently I am just trying to load the file and print the decoded data - but the eventual goal is to print out the lat/long/names of each added point.

KMZ file downloaded from an example custom Google Map https://www.google.com/maps/d/viewer?msa=0&z=11&mid=1KOVdHHEW-aaw2alcteuex4zmunk&ll=50.96764363052866%2C-0.4483580999999903

KMZ file attached: 
[dummy_google_kmz.zip](https://github.com/georust/kml/files/6095093/dummy_google_kmz.zip)

code:
```
use std::path::Path;
use kml::KmlReader;

fn main() {
    let kmz_path = Path::new("test.kmz");
    let mut kmz_reader = KmlReader::<_, f64>::from_kmz_path(kmz_path).unwrap();
    let kmz_data = kmz_reader.read().unwrap();

    println!("{:?}", kmz_data);
}
```

Cargo.toml:
```
[dependencies]
kml = "0.3"
```

backtrace:
```
thread 'main' panicked at 'Error: EscapeError(UnterminatedEntity(13..28))', /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/kml-0.3.0/src/reader.rs:751:56
stack backtrace:
   0:     0x559af518513c - std::backtrace_rs::backtrace::libunwind::trace::hbc0dbba8e4be7fe4
                               at /usr/src/rustc-1.48.0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x559af518513c - std::backtrace_rs::backtrace::trace_unsynchronized::hd8cc0512eb4dd70a
                               at /usr/src/rustc-1.48.0/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x559af518513c - std::sys_common::backtrace::_print_fmt::h766fae1718fafbdd
                               at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:79
   3:     0x559af518513c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha84a0cc4b4a9ee84
                               at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:58
   4:     0x559af51b1b7f - core::fmt::write::h600ac4150cc03aef
                               at /usr/src/rustc-1.48.0/library/core/src/fmt/mod.rs:1080
   5:     0x559af517f565 - std::io::Write::write_fmt::h204ba0c32f2b9a99
                               at /usr/src/rustc-1.48.0/library/std/src/io/mod.rs:1516
   6:     0x559af5196b8d - std::sys_common::backtrace::_print::h6e0f6c74c2c2ad8f
                               at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:61
   7:     0x559af5196b8d - std::sys_common::backtrace::print::h44d505c625eab4ff
                               at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:48
   8:     0x559af5196b8d - std::panicking::default_hook::{{closure}}::h891d2ab61783cea8
                               at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:208
   9:     0x559af5196893 - std::panicking::default_hook::h99e2d300f2614f89
                               at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:227
  10:     0x559af519714f - std::panicking::rust_panic_with_hook::h1b36ee28aa35f9da
                               at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:577
  11:     0x559af5185579 - std::panicking::begin_panic_handler::{{closure}}::h4b50a04380233c65
                               at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:484
  12:     0x559af518528c - std::sys_common::backtrace::__rust_end_short_backtrace::hf274a9700b168e63
                               at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:153
  13:     0x559af5196d52 - rust_begin_unwind
                               at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:483
  14:     0x559af51b3e51 - core::panicking::panic_fmt::hb284f9f2db79ce48
                               at /usr/src/rustc-1.48.0/library/core/src/panicking.rs:85
  15:     0x559af51ad9c3 - core::result::unwrap_failed::h87affc05a8b0ab4b
                               at /usr/src/rustc-1.48.0/library/core/src/result.rs:1220
  16:     0x559af50e03b4 - core::result::Result<T,E>::expect::h0ed01b799c25cb4e
                               at /usr/src/rustc-1.48.0/library/core/src/result.rs:933
  17:     0x559af50ddb3d - kml::reader::KmlReader<B,T>::read_str::h03f02272c39401d2
                               at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/kml-0.3.0/src/reader.rs:751
  18:     0x559af50d241b - kml::reader::KmlReader<B,T>::read_placemark::h1f20ffc5c60dc37d
                               at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/kml-0.3.0/src/reader.rs:314
  19:     0x559af50cf88a - kml::reader::KmlReader<B,T>::read_elements::h87550ba9e30c4f65
                               at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/kml-0.3.0/src/reader.rs:139
  20:     0x559af50cfd0b - kml::reader::KmlReader<B,T>::read_elements::h87550ba9e30c4f65
                               at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/kml-0.3.0/src/reader.rs:146
  21:     0x559af50cfaac - kml::reader::KmlReader<B,T>::read_elements::h87550ba9e30c4f65
                               at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/kml-0.3.0/src/reader.rs:142
  22:     0x559af50dae9b - kml::reader::KmlReader<B,T>::read_kml_document::hca2ae4cd04837891
                               at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/kml-0.3.0/src/reader.rs:184
  23:     0x559af50ce8f2 - kml::reader::KmlReader<B,T>::read_elements::h87550ba9e30c4f65
                               at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/kml-0.3.0/src/reader.rs:127
  24:     0x559af50dd364 - kml::reader::KmlReader<B,T>::read::h689c2e9854e8a4c4
                               at /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/kml-0.3.0/src/reader.rs:107
  25:     0x559af5103a8b - ffw::main::h88092b5e53f8c5be
                               at /home/chris/projects/ffw/src/main.rs:7
  26:     0x559af50fee1b - core::ops::function::FnOnce::call_once::h7e1b76c4a055bd16
                               at /usr/src/rustc-1.48.0/library/core/src/ops/function.rs:227
  27:     0x559af510a30e - std::sys_common::backtrace::__rust_begin_short_backtrace::h20e9080ea383d6d9
                               at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:137
  28:     0x559af50e5321 - std::rt::lang_start::{{closure}}::h1260508dfa92c215
                               at /usr/src/rustc-1.48.0/library/std/src/rt.rs:66
  29:     0x559af5197454 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h473f4d9760584df9
                               at /usr/src/rustc-1.48.0/library/core/src/ops/function.rs:259
  30:     0x559af5197454 - std::panicking::try::do_call::h38b2d68e1990d627
                               at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:381
  31:     0x559af5197454 - std::panicking::try::h6c98453927853dba
                               at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:345
  32:     0x559af5197454 - std::panic::catch_unwind::hf939d3206ba7e318
                               at /usr/src/rustc-1.48.0/library/std/src/panic.rs:382
  33:     0x559af5197454 - std::rt::lang_start_internal::h3c710f42dc1fbba8
                               at /usr/src/rustc-1.48.0/library/std/src/rt.rs:51
  34:     0x559af50e52f7 - std::rt::lang_start::h89631e9ad0445e6d
                               at /usr/src/rustc-1.48.0/library/std/src/rt.rs:65
  35:     0x559af5103c0a - main
  36:     0x7fdddeee1d0a - __libc_start_main
  37:     0x559af50c70ba - _start
  38:                0x0 - <unknown>
```

any tips would be great :)

### PR DESCRIPTION
**Pull request by pjsier**
Closes #1. Currently any issues with UTF-8 decoding cause a panic, so this adds a fallback to `from_utf8_lossy` instead of calling `expect`

### CODE REVIEW

**Review by michaelkirk — APPROVED** [review]

File: src/reader.rs [hunk 1]
```diff
@@ -660,7 +660,10 @@ where
                         .push(self.read_element(&start, start_attrs)?);
                 }
                 Event::Text(ref mut e) => {
-                    element.content = Some(e.unescape_and_decode(&self.reader).expect("Error"))
+                    element.content = Some(
+                        e.unescape_and_decode(&self.reader)
+                            .unwrap_or_else(|_| String::from_utf8_lossy(e.escaped()).to_string()),
```
Comment (michaelkirk) [inline src/reader.rs:665]: seems reasonable!
